import { Fragment } from "react";
import Head from "next/head";
import { NextPage } from "next";

const Home: NextPage = () => {
    return (
        <Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link
                    href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <main className="flex justify-center items-center w-full">
                Main Page
            </main>
        </Fragment>
    );
};

export default Home;
